### ISSUE TITLE
http support

### ISSUE THREAD

**Issue by waclaw66** [heximcz/kresd-stats-zabbix#1]
Hi!
Support for optional http protocol would be nice. There is https harcoded.

Thanks!

**Comment by heximcz** [comment]
Hi,
check last commit please. Let me know.

**Comment by waclaw66** [comment]
```
In PrepareJsonDataCommand.php line 88:
  Value: http is not equal to http or https

```
There should be `&&` instead `||` ;)

**Comment by heximcz** [comment]
ouu :-) You are right.

**Comment by waclaw66** [comment]
Now it works. Thanks!
